"tag" = { fg = "red" }
"attribute" = { fg = "yellow" }
"comment" = { fg = "dark-gray", modifiers = ["italic"] }
"constant" = { fg = "cyan" }
"constant.numeric" = { fg = "orange" }
"constant.builtin" = { fg = "orange" }
"constant.character.escape" = { fg = "orange" }
"constructor" = { fg = "green" }
"function" = { fg = "blue" }
"function.builtin" = { fg = "green" }
"function.macro" = { fg = "purple" }
"keyword" = { fg = "blue" }
"keyword.control" = { fg = "purple" }
"keyword.control.import" = { fg = "red" }
"keyword.directive" = { fg = "purple" }
"keyword.storage" = { fg = "purple" }
"label" = { fg = "purple" }
"namespace" = { fg = "blue" }
"operator" = { fg = "purple" }
"keyword.operator" = { fg = "purple" }
"special" = { fg = "blue" }
"string" = { fg = "green" }
"type" = { fg = "yellow" }
"variable" = { fg = "light-gray" }
"variable.builtin" = { fg = "blue" }
"variable.parameter" = { fg = "red" }
"variable.other.member" = { fg = "red" }

"markup.heading" = { fg = "red" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"] }
"markup.link.text" = { fg = "purple" }

"diff.plus" = "green"
"diff.delta" = "orange"
"diff.minus" = "red"

"diagnostic.info".underline = { color = "blue", style = "curl" }
"diagnostic.hint".underline = { color = "green", style = "curl" }
"diagnostic.warning".underline = { color = "yellow", style = "curl" }
"diagnostic.error".underline = { color = "red", style = "curl" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"ui.background" = {}
"ui.virtual" = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "faint-gray" }
"ui.virtual.whitespace" = { fg = "light-gray" }
"ui.virtual.ruler" = { bg = "gray" }
"ui.virtual.inlay-hint" = { fg = "light-gray" }
"ui.virtual.jump-label" = { fg = "light-gray", modifiers = ["bold"] }

"ui.cursor" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "light-gray", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "blue", modifiers = ["underlined"] }

"ui.selection" = { bg = "light-black" }
"ui.selection.primary" = { bg = "dark-gray" }
"ui.cursorline.primary" = { bg = "light-black" }

"ui.highlight" = { bg = "gray" }
"ui.highlight.frameline" = { bg = "#97202a" }

"ui.linenr" = { fg = "dark-gray" }
"ui.linenr.selected" = { fg = "light-gray" }

"ui.statusline" = { fg = "light-gray", bg = "black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
"ui.statusline.normal" = { fg = "light-black", bg = "blue", modifiers = [
    "bold",
] }
"ui.statusline.insert" = { fg = "light-black", bg = "green", modifiers = [
    "bold",
] }
"ui.statusline.select" = { fg = "light-black", bg = "purple", modifiers = [
    "bold",
] }

"ui.bufferline" = { fg = "dark-gray", bg = "black" }
"ui.bufferline.active" = { fg = "black", bg = "blue", underline = { color = "light-black", style = "line" } }
"ui.bufferline.background" = { bg = "black" }

"ui.text" = { fg = "faint-gray" }
"ui.text.focus" = { fg = "faint-gray", bg = "light-black", modifiers = [
    "bold",
] }

"ui.help" = { fg = "faint-gray", bg = "light-black" }
"ui.popup" = { bg = "light-black" }
"ui.window" = { fg = "light-black" }
"ui.menu" = { fg = "faint-gray", bg = "light-black" }
"ui.menu.selected" = { fg = "black", bg = "blue" }
"ui.menu.scroll" = { fg = "faint-gray", bg = "faint-gray" }

"ui.debug" = { fg = "red" }

[palette]
black = "#1b2b34"
light-black = "#343d46"
dark-gray = "#4f5b66"
gray = "#65737e"
faint-gray = "#a7adba"
light-gray = "#c0c5ce"
dark-white = "#cdd3de"
white = "#d8dee9"

red = "#db686b"
orange = "#f99157"
yellow = "#f2ca73"
green = "#a2c699"
cyan = "#74b1b2"
blue = "#7198c8"
purple = "#c594c5"
brown = "#ab7967"
